lib/test_weather_web/router.ex
defmodule TestWeatherWeb.Router do
  use TestWeatherWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TestWeatherWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TestWeatherWeb do
    pipe_through :browser

    resources "/specs", SpecController
    resources "/tickets", TicketController
    post "/tickets-import", TicketController, :import
    post "/export", ExportController, :create
    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", TestWeatherWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: TestWeatherWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/test_weather/report/ticket.ex
defmodule TestWeather.Report.Ticket do
  use Ecto.Schema
  import Ecto.Changeset

  schema "tickets" do
    field :airline, :string
    field :destination, :string
    field :destination_iata_code, :string
    field :destination_latitude, :string
    field :destination_longitude, :string
    field :destination_name, :string
    field :flight_num, :string
    field :origin, :string
    field :origin_iata_code, :string
    field :origin_latitude, :string
    field :origin_longitude, :string
    field :origin_name, :string

    timestamps()
  end

  @doc false
  def changeset(ticket, attrs) do
    ticket
    |> cast(attrs, [:origin, :destination, :airline, :flight_num, :origin_iata_code, :origin_name, :origin_latitude, :origin_longitude, :destination_iata_code, :destination_name, :destination_latitude, :destination_longitude])
    |> validate_required([:origin, :destination, :airline, :flight_num, :origin_iata_code, :origin_name, :origin_latitude, :origin_longitude, :destination_iata_code, :destination_name, :destination_latitude, :destination_longitude])
  end
end

lib/test_weather_web/controllers/ticket_controller.ex
defmodule TestWeatherWeb.TicketController do
  use TestWeatherWeb, :controller

  alias TestWeather.Report
  alias TestWeather.Report.Ticket

  def index(conn, _params) do
    tickets = Report.list_tickets()
    render(conn, "index.html", tickets: tickets)
  end

  def new(conn, _params) do
    changeset = Report.change_ticket(%Ticket{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"ticket" => ticket_params}) do
    case Report.create_ticket(ticket_params) do
      {:ok, ticket} ->
        conn
        |> put_flash(:info, "Ticket created successfully.")
        |> redirect(to: Routes.ticket_path(conn, :show, ticket))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    ticket = Report.get_ticket!(id)
    render(conn, "show.html", ticket: ticket)
  end

  def edit(conn, %{"id" => id}) do
    ticket = Report.get_ticket!(id)
    changeset = Report.change_ticket(ticket)
    render(conn, "edit.html", ticket: ticket, changeset: changeset)
  end

  def update(conn, %{"id" => id, "ticket" => ticket_params}) do
    ticket = Report.get_ticket!(id)

    case Report.update_ticket(ticket, ticket_params) do
      {:ok, ticket} ->
        conn
        |> put_flash(:info, "Ticket updated successfully.")
        |> redirect(to: Routes.ticket_path(conn, :show, ticket))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", ticket: ticket, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    ticket = Report.get_ticket!(id)
    {:ok, _ticket} = Report.delete_ticket(ticket)

    conn
    |> put_flash(:info, "Ticket deleted successfully.")
    |> redirect(to: Routes.ticket_path(conn, :index))
  end

  def import(conn, %{"csv" => csv}) do
    data = csv_decoder(csv)
    import_tickets(data)

    conn
      |> put_flash(:info, "Tickets importados exitosamente!")
      |> redirect(to: Routes.ticket_path(conn, :index))
  end

  defp csv_decoder(file) do
    "#{file.path}"
      |> Path.expand(__DIR__)
      |> File.stream!()
      |> CSV.decode(headers: true)
      |> Enum.map(fn data -> data end)
  end

  def import_tickets(data) do
    tickets = Enum.map(data, fn {:ok, ticket} -> parse(ticket) end)
    params = Report.convert_params(tickets)

    {_, _} = Report.insert_tickets(params)
  end

  defp parse(ticket) do
    Report.parse_fields(ticket)
  end
end

lib/test_weather_web/views/ticket_view.ex
defmodule TestWeatherWeb.TicketView do
  use TestWeatherWeb, :view
end

lib/test_weather_web/templates/ticket/edit.html.heex
<h1>Edit Ticket</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.ticket_path(@conn,
:update, @ticket)) %>

<span><%= link "<- Atras", to: Routes.ticket_path(@conn, :index) %></span>

lib/test_weather_web/templates/ticket/form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :origin %>
  <%= text_input f, :origin %>
  <%= error_tag f, :origin %>

  <%= label f, :destination %>
  <%= text_input f, :destination %>
  <%= error_tag f, :destination %>

  <%= label f, :airline %>
  <%= text_input f, :airline %>
  <%= error_tag f, :airline %>

  <%= label f, :flight_num %>
  <%= text_input f, :flight_num %>
  <%= error_tag f, :flight_num %>

  <%= label f, :origin_iata_code %>
  <%= text_input f, :origin_iata_code %>
  <%= error_tag f, :origin_iata_code %>

  <%= label f, :origin_name %>
  <%= text_input f, :origin_name %>
  <%= error_tag f, :origin_name %>

  <%= label f, :origin_latitude %>
  <%= text_input f, :origin_latitude %>
  <%= error_tag f, :origin_latitude %>

  <%= label f, :origin_longitude %>
  <%= text_input f, :origin_longitude %>
  <%= error_tag f, :origin_longitude %>

  <%= label f, :destination_iata_code %>
  <%= text_input f, :destination_iata_code %>
  <%= error_tag f, :destination_iata_code %>

  <%= label f, :destination_name %>
  <%= text_input f, :destination_name %>
  <%= error_tag f, :destination_name %>

  <%= label f, :destination_latitude %>
  <%= text_input f, :destination_latitude %>
  <%= error_tag f, :destination_latitude %>

  <%= label f, :destination_longitude %>
  <%= text_input f, :destination_longitude %>
  <%= error_tag f, :destination_longitude %>

  <div>
    <%= submit "Guardar" %>
  </div>
</.form>

lib/test_weather_web/templates/ticket/index.html.heex
<h1>Reporte de Tickets</h1>

<section class="phx-hero">
  <div class="flex justify-end mb-2">
    <%= link to: Routes.spec_path(@conn, :index) do %>
    <div><%= submit "Calcular Clima" %></div>
    <% end %>
  </div>
</section>

<table>
  <td>
    <div style="text-align: left">
      <span><%= link "Regresar", to: Routes.page_path(@conn, :index) %></span>
    </div>
  </td>
</table>

<table>
  <thead>
    <tr>
      <th>Origin</th>
      <th>Destination</th>
      <th>Airline</th>
      <th>Flight num</th>
      <th>Origin iata code</th>
      <th>Origin name</th>
      <th>Origin latitude</th>
      <th>Origin longitude</th>
      <th>Destination iata code</th>
      <th>Destination name</th>
      <th>Destination latitude</th>
      <th>Destination longitude</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for ticket <- @tickets do %>
    <tr>
      <td><%= ticket.origin %></td>
      <td><%= ticket.destination %></td>
      <td><%= ticket.airline %></td>
      <td><%= ticket.flight_num %></td>
      <td><%= ticket.origin_iata_code %></td>
      <td><%= ticket.origin_name %></td>
      <td><%= ticket.origin_latitude %></td>
      <td><%= ticket.origin_longitude %></td>
      <td><%= ticket.destination_iata_code %></td>
      <td><%= ticket.destination_name %></td>
      <td><%= ticket.destination_latitude %></td>
      <td><%= ticket.destination_longitude %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<table>
  <td>
    <div style="text-align: left">
      <span><%= link "Regresar", to: Routes.page_path(@conn, :index) %></span>
    </div>
  </td>
</table>

lib/test_weather_web/templates/ticket/new.html.heex
<h1>Nuevo Ticket</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.ticket_path(@conn,
:create)) %>

<span><%= link "<- Atras", to: Routes.ticket_path(@conn, :index) %></span>

lib/test_weather_web/templates/ticket/show.html.heex
<h1>Ver Ticket</h1>

<ul>
  <li>
    <strong>Origin:</strong>
    <%= @ticket.origin %>
  </li>

  <li>
    <strong>Destination:</strong>
    <%= @ticket.destination %>
  </li>

  <li>
    <strong>Airline:</strong>
    <%= @ticket.airline %>
  </li>

  <li>
    <strong>Flight num:</strong>
    <%= @ticket.flight_num %>
  </li>

  <li>
    <strong>Origin iata code:</strong>
    <%= @ticket.origin_iata_code %>
  </li>

  <li>
    <strong>Origin name:</strong>
    <%= @ticket.origin_name %>
  </li>

  <li>
    <strong>Origin latitude:</strong>
    <%= @ticket.origin_latitude %>
  </li>

  <li>
    <strong>Origin longitude:</strong>
    <%= @ticket.origin_longitude %>
  </li>

  <li>
    <strong>Destination iata code:</strong>
    <%= @ticket.destination_iata_code %>
  </li>

  <li>
    <strong>Destination name:</strong>
    <%= @ticket.destination_name %>
  </li>

  <li>
    <strong>Destination latitude:</strong>
    <%= @ticket.destination_latitude %>
  </li>

  <li>
    <strong>Destination longitude:</strong>
    <%= @ticket.destination_longitude %>
  </li>
</ul>

<span><%= link "Editar", to: Routes.ticket_path(@conn, :edit, @ticket) %></span>
|
<span><%= link "<- Atras", to: Routes.ticket_path(@conn, :index) %></span>